version: "3.9"

services:
  api:
    container_name: api_clients
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=kennedy
      - DB_PASSWORD=1234
      - DB=clients_database
      - SECRET_KEY=4677a9b26c5183a563cabf35426cb82a
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db_clients
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=kennedy
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=clients_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kennedy -d clients_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - project_full_stack:/var/lib/postgresql/data
volumes:
  project_full_stack:
    driver: local
